### ISSUE TITLE
[REQUEST] Add balance From Console

### ISSUE THREAD

**Issue by SuryaRajgor** [Gunpowder-MC/GunpowderCurrency#5]
Hello I want to add balance to Reward for server votes
so i add this (balance %PLAYER% add 10'
also, try the direct 'AdminAdd  %PLAYER% 10 ') command to votifier its Show "A player is required to run this command here" in console

**Comment by CamperSamu** [comment]
I coded a small addon to add a /opbalance command, until this is fixed you can use this: https://github.com/CamperSamu/MoneyHack

compiled jars are in github actions.
(I'd like to open a pr but I don't really know kothlin + I legit can't understand what's causing the issue, but using brigadier + fapi permissions separetely does the trick...)

**Comment by Martmists-GH** [comment]
It seems this is an issue with the permissions API I was using, I'll revisit this when a good new permission API exists.
