### ISSUE TITLE
Server Crashes (or does nothing with more mods enabled) when trying to sell/buy claim blocks with Flan

### ISSUE THREAD

**Issue by pahanakun** [Gunpowder-MC/GunpowderCurrency#7]
When I first tried to buy/sell claimblocks with my full mod list, nothing happens. Flan's claimblocks don't increase, and /balance is unchanged.

The issue occurs with multiple buy/sell prices for claim blocks (1, 20, 25 etc)

full modlist: https://pastebin.com/1dVMwd8r

When disabling all mods except for gunpowder (and currency module), flan, fabric-api and kotlin, the problem gets worse: the server just crashes.

- Minecraft: 1.18.1
- Fabric(API): 0.45.0+1.18
- Fabric loader: 0.12.12
- Flan: 1.18-1.6.6
- gunpowder-base-1.1.1.1+1.18.1
- gunpowder-currency-1.0.8+gunpowder.1.1.1.1.mc.1.18.1

error in server console: https://pastebin.com/CuDp47d5
crash report: https://pastebin.com/UHrLChcF

Also posted this issue on the flan github page

**Comment by Martmists-GH** [comment]
This is a bug with Flan, as they use an old version of our API.
